using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using InfServer.Network;

namespace InfServer.Protocol
{	/// <summary>
	/// CS_Initial is the first greeting packet sent from the game client
	/// </summary>
	public class CS_Initial : PacketBase
	{	// Member Variables
		///////////////////////////////////////////////////
		public Int32 CRCLength;			//Suggestion for the crc length?
		public Int32 connectionID;		//A random connection ID, generated by the client
		public Int32 udpMaxPacket;		//The maximum packet size

		//Packet routing
		public const ushort TypeID = 1;
		static public event Action<CS_Initial, Client> Handlers;


		///////////////////////////////////////////////////
		// Member Functions
		//////////////////////////////////////////////////
		/// <summary>
		/// Creates an instance of the dummy packet used to debug communication or 
		/// to represent unknown packets.
		/// </summary>
		/// <param name="typeID">The type of the received packet.</param>
		/// <param name="buffer">The received data.</param>
		public CS_Initial(ushort typeID, byte[] buffer, int index, int count)
			: base(typeID, buffer, index, count)
		{
		}

		/// <summary>
		/// Routes a new packet to various relevant handlers
		/// </summary>
		public override void Route()
		{	//Call all handlers!
			if (Handlers != null)
				Handlers(this, (Client)_client);
		}

		/// <summary>
		/// Deserializes the data present in the packet contents into data fields in the class.
		/// </summary>
		public override void Deserialize()
		{	//Retrieve values
			CRCLength = Flip(_contentReader.ReadInt32());
			connectionID = Flip(_contentReader.ReadInt32());
			udpMaxPacket = Flip(_contentReader.ReadInt32());
		}

		/// <summary>
		/// Returns a meaningful of the packet's data
		/// </summary>
		public override string Dump
		{
			get
			{
				return "UDP Max:: " + udpMaxPacket + " / CRCLen: " + CRCLength;
			}
		}
	}
}
