#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfServer.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class InfantryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertplayer(InfServer.Data.DB.player instance);
    partial void Updateplayer(InfServer.Data.DB.player instance);
    partial void Deleteplayer(InfServer.Data.DB.player instance);
    partial void Insertstats(InfServer.Data.DB.stats instance);
    partial void Updatestats(InfServer.Data.DB.stats instance);
    partial void Deletestats(InfServer.Data.DB.stats instance);
    partial void Insertaccount(InfServer.Data.DB.account instance);
    partial void Updateaccount(InfServer.Data.DB.account instance);
    partial void Deleteaccount(InfServer.Data.DB.account instance);
    partial void Insertzone(InfServer.Data.DB.zone instance);
    partial void Updatezone(InfServer.Data.DB.zone instance);
    partial void Deletezone(InfServer.Data.DB.zone instance);
    partial void Insertalias(InfServer.Data.DB.alias instance);
    partial void Updatealias(InfServer.Data.DB.alias instance);
    partial void Deletealias(InfServer.Data.DB.alias instance);
    partial void Insertsquad(InfServer.Data.DB.squad instance);
    partial void Updatesquad(InfServer.Data.DB.squad instance);
    partial void Deletesquad(InfServer.Data.DB.squad instance);
    #endregion
		
		public InfantryDataContext() : 
				base(global::InfDatabase.Properties.Settings.Default.DataSourceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InfantryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfantryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfantryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfantryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<InfServer.Data.DB.player> players
		{
			get
			{
				return this.GetTable<InfServer.Data.DB.player>();
			}
		}
		
		public System.Data.Linq.Table<InfServer.Data.DB.stats> stats
		{
			get
			{
				return this.GetTable<InfServer.Data.DB.stats>();
			}
		}
		
		public System.Data.Linq.Table<InfServer.Data.DB.account> accounts
		{
			get
			{
				return this.GetTable<InfServer.Data.DB.account>();
			}
		}
		
		public System.Data.Linq.Table<InfServer.Data.DB.zone> zones
		{
			get
			{
				return this.GetTable<InfServer.Data.DB.zone>();
			}
		}
		
		public System.Data.Linq.Table<InfServer.Data.DB.alias> alias
		{
			get
			{
				return this.GetTable<InfServer.Data.DB.alias>();
			}
		}
		
		public System.Data.Linq.Table<InfServer.Data.DB.squad> squads
		{
			get
			{
				return this.GetTable<InfServer.Data.DB.squad>();
			}
		}
	}
}
namespace InfServer.Data.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[Table(Name="dbo.player")]
	public partial class player : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _alias;
		
		private long _zone;
		
		private System.Nullable<long> _squad;
		
		private long _stats;
		
		private short _permission;
		
		private System.DateTime _lastAccess;
		
		private System.Data.Linq.Binary _inventory;
		
		private System.Data.Linq.Binary _skills;
		
		private EntityRef<stats> _stats1;
		
		private EntityRef<zone> _zone1;
		
		private EntityRef<alias> _alias1;
		
		private EntityRef<squad> _squad1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnaliasChanging(long value);
    partial void OnaliasChanged();
    partial void OnzoneChanging(long value);
    partial void OnzoneChanged();
    partial void OnsquadChanging(System.Nullable<long> value);
    partial void OnsquadChanged();
    partial void OnstatsChanging(long value);
    partial void OnstatsChanged();
    partial void OnpermissionChanging(short value);
    partial void OnpermissionChanged();
    partial void OnlastAccessChanging(System.DateTime value);
    partial void OnlastAccessChanged();
    partial void OninventoryChanging(System.Data.Linq.Binary value);
    partial void OninventoryChanged();
    partial void OnskillsChanging(System.Data.Linq.Binary value);
    partial void OnskillsChanged();
    #endregion
		
		public player()
		{
			this._stats1 = default(EntityRef<stats>);
			this._zone1 = default(EntityRef<zone>);
			this._alias1 = default(EntityRef<alias>);
			this._squad1 = default(EntityRef<squad>);
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_alias", DbType="BigInt NOT NULL")]
		public long alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					if (this._alias1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[Column(Storage="_zone", DbType="BigInt NOT NULL")]
		public long zone
		{
			get
			{
				return this._zone;
			}
			set
			{
				if ((this._zone != value))
				{
					if (this._zone1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnzoneChanging(value);
					this.SendPropertyChanging();
					this._zone = value;
					this.SendPropertyChanged("zone");
					this.OnzoneChanged();
				}
			}
		}
		
		[Column(Storage="_squad", DbType="BigInt")]
		public System.Nullable<long> squad
		{
			get
			{
				return this._squad;
			}
			set
			{
				if ((this._squad != value))
				{
					if (this._squad1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsquadChanging(value);
					this.SendPropertyChanging();
					this._squad = value;
					this.SendPropertyChanged("squad");
					this.OnsquadChanged();
				}
			}
		}
		
		[Column(Storage="_stats", DbType="BigInt NOT NULL")]
		public long stats
		{
			get
			{
				return this._stats;
			}
			set
			{
				if ((this._stats != value))
				{
					if (this._stats1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstatsChanging(value);
					this.SendPropertyChanging();
					this._stats = value;
					this.SendPropertyChanged("stats");
					this.OnstatsChanged();
				}
			}
		}
		
		[Column(Storage="_permission", DbType="SmallInt NOT NULL")]
		public short permission
		{
			get
			{
				return this._permission;
			}
			set
			{
				if ((this._permission != value))
				{
					this.OnpermissionChanging(value);
					this.SendPropertyChanging();
					this._permission = value;
					this.SendPropertyChanged("permission");
					this.OnpermissionChanged();
				}
			}
		}
		
		[Column(Storage="_lastAccess", DbType="DateTime NOT NULL")]
		public System.DateTime lastAccess
		{
			get
			{
				return this._lastAccess;
			}
			set
			{
				if ((this._lastAccess != value))
				{
					this.OnlastAccessChanging(value);
					this.SendPropertyChanging();
					this._lastAccess = value;
					this.SendPropertyChanged("lastAccess");
					this.OnlastAccessChanged();
				}
			}
		}
		
		[Column(Storage="_inventory", DbType="VarBinary(512)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary inventory
		{
			get
			{
				return this._inventory;
			}
			set
			{
				if ((this._inventory != value))
				{
					this.OninventoryChanging(value);
					this.SendPropertyChanging();
					this._inventory = value;
					this.SendPropertyChanged("inventory");
					this.OninventoryChanged();
				}
			}
		}
		
		[Column(Storage="_skills", DbType="VarBinary(512)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary skills
		{
			get
			{
				return this._skills;
			}
			set
			{
				if ((this._skills != value))
				{
					this.OnskillsChanging(value);
					this.SendPropertyChanging();
					this._skills = value;
					this.SendPropertyChanged("skills");
					this.OnskillsChanged();
				}
			}
		}
		
		[Association(Name="stats_player", Storage="_stats1", ThisKey="stats", IsForeignKey=true)]
		public stats stats1
		{
			get
			{
				return this._stats1.Entity;
			}
			set
			{
				stats previousValue = this._stats1.Entity;
				if (((previousValue != value) 
							|| (this._stats1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._stats1.Entity = null;
						previousValue.players.Remove(this);
					}
					this._stats1.Entity = value;
					if ((value != null))
					{
						value.players.Add(this);
						this._stats = value.id;
					}
					else
					{
						this._stats = default(long);
					}
					this.SendPropertyChanged("stats1");
				}
			}
		}
		
		[Association(Name="zone_player", Storage="_zone1", ThisKey="zone", IsForeignKey=true)]
		public zone zone1
		{
			get
			{
				return this._zone1.Entity;
			}
			set
			{
				zone previousValue = this._zone1.Entity;
				if (((previousValue != value) 
							|| (this._zone1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._zone1.Entity = null;
						previousValue.players.Remove(this);
					}
					this._zone1.Entity = value;
					if ((value != null))
					{
						value.players.Add(this);
						this._zone = value.id;
					}
					else
					{
						this._zone = default(long);
					}
					this.SendPropertyChanged("zone1");
				}
			}
		}
		
		[Association(Name="alia_player", Storage="_alias1", ThisKey="alias", IsForeignKey=true)]
		public alias alias1
		{
			get
			{
				return this._alias1.Entity;
			}
			set
			{
				alias previousValue = this._alias1.Entity;
				if (((previousValue != value) 
							|| (this._alias1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._alias1.Entity = null;
						previousValue.players.Remove(this);
					}
					this._alias1.Entity = value;
					if ((value != null))
					{
						value.players.Add(this);
						this._alias = value.id;
					}
					else
					{
						this._alias = default(long);
					}
					this.SendPropertyChanged("alias1");
				}
			}
		}
		
		[Association(Name="squad_player", Storage="_squad1", ThisKey="squad", IsForeignKey=true)]
		public squad squad1
		{
			get
			{
				return this._squad1.Entity;
			}
			set
			{
				squad previousValue = this._squad1.Entity;
				if (((previousValue != value) 
							|| (this._squad1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._squad1.Entity = null;
						previousValue.players.Remove(this);
					}
					this._squad1.Entity = value;
					if ((value != null))
					{
						value.players.Add(this);
						this._squad = value.id;
					}
					else
					{
						this._squad = default(Nullable<long>);
					}
					this.SendPropertyChanged("squad1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.stats")]
	public partial class stats : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private int _cash;
		
		private int _experience;
		
		private int _experienceTotal;
		
		private int _points;
		
		private int _killPoints;
		
		private int _deathPoints;
		
		private int _assistPoints;
		
		private int _bonusPoints;
		
		private int _vehicleKills;
		
		private int _vehicleDeaths;
		
		private int _playSeconds;
		
		private int _altstat1;
		
		private int _altstat2;
		
		private int _altstat3;
		
		private int _altstat4;
		
		private int _altstat5;
		
		private int _altstat6;
		
		private int _altstat7;
		
		private int _altstat8;
		
		private EntitySet<player> _players;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OncashChanging(int value);
    partial void OncashChanged();
    partial void OnexperienceChanging(int value);
    partial void OnexperienceChanged();
    partial void OnexperienceTotalChanging(int value);
    partial void OnexperienceTotalChanged();
    partial void OnpointsChanging(int value);
    partial void OnpointsChanged();
    partial void OnkillPointsChanging(int value);
    partial void OnkillPointsChanged();
    partial void OndeathPointsChanging(int value);
    partial void OndeathPointsChanged();
    partial void OnassistPointsChanging(int value);
    partial void OnassistPointsChanged();
    partial void OnbonusPointsChanging(int value);
    partial void OnbonusPointsChanged();
    partial void OnvehicleKillsChanging(int value);
    partial void OnvehicleKillsChanged();
    partial void OnvehicleDeathsChanging(int value);
    partial void OnvehicleDeathsChanged();
    partial void OnplaySecondsChanging(int value);
    partial void OnplaySecondsChanged();
    partial void Onaltstat1Changing(int value);
    partial void Onaltstat1Changed();
    partial void Onaltstat2Changing(int value);
    partial void Onaltstat2Changed();
    partial void Onaltstat3Changing(int value);
    partial void Onaltstat3Changed();
    partial void Onaltstat4Changing(int value);
    partial void Onaltstat4Changed();
    partial void Onaltstat5Changing(int value);
    partial void Onaltstat5Changed();
    partial void Onaltstat6Changing(int value);
    partial void Onaltstat6Changed();
    partial void Onaltstat7Changing(int value);
    partial void Onaltstat7Changed();
    partial void Onaltstat8Changing(int value);
    partial void Onaltstat8Changed();
    #endregion
		
		public stats()
		{
			this._players = new EntitySet<player>(new Action<player>(this.attach_players), new Action<player>(this.detach_players));
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_cash", DbType="Int NOT NULL")]
		public int cash
		{
			get
			{
				return this._cash;
			}
			set
			{
				if ((this._cash != value))
				{
					this.OncashChanging(value);
					this.SendPropertyChanging();
					this._cash = value;
					this.SendPropertyChanged("cash");
					this.OncashChanged();
				}
			}
		}
		
		[Column(Storage="_experience", DbType="Int NOT NULL")]
		public int experience
		{
			get
			{
				return this._experience;
			}
			set
			{
				if ((this._experience != value))
				{
					this.OnexperienceChanging(value);
					this.SendPropertyChanging();
					this._experience = value;
					this.SendPropertyChanged("experience");
					this.OnexperienceChanged();
				}
			}
		}
		
		[Column(Storage="_experienceTotal", DbType="Int NOT NULL")]
		public int experienceTotal
		{
			get
			{
				return this._experienceTotal;
			}
			set
			{
				if ((this._experienceTotal != value))
				{
					this.OnexperienceTotalChanging(value);
					this.SendPropertyChanging();
					this._experienceTotal = value;
					this.SendPropertyChanged("experienceTotal");
					this.OnexperienceTotalChanged();
				}
			}
		}
		
		[Column(Storage="_points", DbType="Int NOT NULL")]
		public int points
		{
			get
			{
				return this._points;
			}
			set
			{
				if ((this._points != value))
				{
					this.OnpointsChanging(value);
					this.SendPropertyChanging();
					this._points = value;
					this.SendPropertyChanged("points");
					this.OnpointsChanged();
				}
			}
		}
		
		[Column(Storage="_killPoints", DbType="Int NOT NULL")]
		public int killPoints
		{
			get
			{
				return this._killPoints;
			}
			set
			{
				if ((this._killPoints != value))
				{
					this.OnkillPointsChanging(value);
					this.SendPropertyChanging();
					this._killPoints = value;
					this.SendPropertyChanged("killPoints");
					this.OnkillPointsChanged();
				}
			}
		}
		
		[Column(Storage="_deathPoints", DbType="Int NOT NULL")]
		public int deathPoints
		{
			get
			{
				return this._deathPoints;
			}
			set
			{
				if ((this._deathPoints != value))
				{
					this.OndeathPointsChanging(value);
					this.SendPropertyChanging();
					this._deathPoints = value;
					this.SendPropertyChanged("deathPoints");
					this.OndeathPointsChanged();
				}
			}
		}
		
		[Column(Storage="_assistPoints", DbType="Int NOT NULL")]
		public int assistPoints
		{
			get
			{
				return this._assistPoints;
			}
			set
			{
				if ((this._assistPoints != value))
				{
					this.OnassistPointsChanging(value);
					this.SendPropertyChanging();
					this._assistPoints = value;
					this.SendPropertyChanged("assistPoints");
					this.OnassistPointsChanged();
				}
			}
		}
		
		[Column(Storage="_bonusPoints", DbType="Int NOT NULL")]
		public int bonusPoints
		{
			get
			{
				return this._bonusPoints;
			}
			set
			{
				if ((this._bonusPoints != value))
				{
					this.OnbonusPointsChanging(value);
					this.SendPropertyChanging();
					this._bonusPoints = value;
					this.SendPropertyChanged("bonusPoints");
					this.OnbonusPointsChanged();
				}
			}
		}
		
		[Column(Storage="_vehicleKills", DbType="Int NOT NULL")]
		public int vehicleKills
		{
			get
			{
				return this._vehicleKills;
			}
			set
			{
				if ((this._vehicleKills != value))
				{
					this.OnvehicleKillsChanging(value);
					this.SendPropertyChanging();
					this._vehicleKills = value;
					this.SendPropertyChanged("vehicleKills");
					this.OnvehicleKillsChanged();
				}
			}
		}
		
		[Column(Storage="_vehicleDeaths", DbType="Int NOT NULL")]
		public int vehicleDeaths
		{
			get
			{
				return this._vehicleDeaths;
			}
			set
			{
				if ((this._vehicleDeaths != value))
				{
					this.OnvehicleDeathsChanging(value);
					this.SendPropertyChanging();
					this._vehicleDeaths = value;
					this.SendPropertyChanged("vehicleDeaths");
					this.OnvehicleDeathsChanged();
				}
			}
		}
		
		[Column(Storage="_playSeconds", DbType="Int NOT NULL")]
		public int playSeconds
		{
			get
			{
				return this._playSeconds;
			}
			set
			{
				if ((this._playSeconds != value))
				{
					this.OnplaySecondsChanging(value);
					this.SendPropertyChanging();
					this._playSeconds = value;
					this.SendPropertyChanged("playSeconds");
					this.OnplaySecondsChanged();
				}
			}
		}
		
		[Column(Storage="_altstat1", DbType="Int NOT NULL")]
		public int altstat1
		{
			get
			{
				return this._altstat1;
			}
			set
			{
				if ((this._altstat1 != value))
				{
					this.Onaltstat1Changing(value);
					this.SendPropertyChanging();
					this._altstat1 = value;
					this.SendPropertyChanged("altstat1");
					this.Onaltstat1Changed();
				}
			}
		}
		
		[Column(Storage="_altstat2", DbType="Int NOT NULL")]
		public int altstat2
		{
			get
			{
				return this._altstat2;
			}
			set
			{
				if ((this._altstat2 != value))
				{
					this.Onaltstat2Changing(value);
					this.SendPropertyChanging();
					this._altstat2 = value;
					this.SendPropertyChanged("altstat2");
					this.Onaltstat2Changed();
				}
			}
		}
		
		[Column(Storage="_altstat3", DbType="Int NOT NULL")]
		public int altstat3
		{
			get
			{
				return this._altstat3;
			}
			set
			{
				if ((this._altstat3 != value))
				{
					this.Onaltstat3Changing(value);
					this.SendPropertyChanging();
					this._altstat3 = value;
					this.SendPropertyChanged("altstat3");
					this.Onaltstat3Changed();
				}
			}
		}
		
		[Column(Storage="_altstat4", DbType="Int NOT NULL")]
		public int altstat4
		{
			get
			{
				return this._altstat4;
			}
			set
			{
				if ((this._altstat4 != value))
				{
					this.Onaltstat4Changing(value);
					this.SendPropertyChanging();
					this._altstat4 = value;
					this.SendPropertyChanged("altstat4");
					this.Onaltstat4Changed();
				}
			}
		}
		
		[Column(Storage="_altstat5", DbType="Int NOT NULL")]
		public int altstat5
		{
			get
			{
				return this._altstat5;
			}
			set
			{
				if ((this._altstat5 != value))
				{
					this.Onaltstat5Changing(value);
					this.SendPropertyChanging();
					this._altstat5 = value;
					this.SendPropertyChanged("altstat5");
					this.Onaltstat5Changed();
				}
			}
		}
		
		[Column(Storage="_altstat6", DbType="Int NOT NULL")]
		public int altstat6
		{
			get
			{
				return this._altstat6;
			}
			set
			{
				if ((this._altstat6 != value))
				{
					this.Onaltstat6Changing(value);
					this.SendPropertyChanging();
					this._altstat6 = value;
					this.SendPropertyChanged("altstat6");
					this.Onaltstat6Changed();
				}
			}
		}
		
		[Column(Storage="_altstat7", DbType="Int NOT NULL")]
		public int altstat7
		{
			get
			{
				return this._altstat7;
			}
			set
			{
				if ((this._altstat7 != value))
				{
					this.Onaltstat7Changing(value);
					this.SendPropertyChanging();
					this._altstat7 = value;
					this.SendPropertyChanged("altstat7");
					this.Onaltstat7Changed();
				}
			}
		}
		
		[Column(Storage="_altstat8", DbType="Int NOT NULL")]
		public int altstat8
		{
			get
			{
				return this._altstat8;
			}
			set
			{
				if ((this._altstat8 != value))
				{
					this.Onaltstat8Changing(value);
					this.SendPropertyChanging();
					this._altstat8 = value;
					this.SendPropertyChanged("altstat8");
					this.Onaltstat8Changed();
				}
			}
		}
		
		[Association(Name="stats_player", Storage="_players", OtherKey="stats")]
		public EntitySet<player> players
		{
			get
			{
				return this._players;
			}
			set
			{
				this._players.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_players(player entity)
		{
			this.SendPropertyChanging();
			entity.stats1 = this;
		}
		
		private void detach_players(player entity)
		{
			this.SendPropertyChanging();
			entity.stats1 = null;
		}
	}
	
	[Table(Name="dbo.account")]
	public partial class account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
		private string _password;
		
		private string _ticket;
		
		private System.DateTime _dateCreated;
		
		private System.DateTime _lastAccess;
		
		private int _permission;
		
		private EntitySet<alias> _alias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnticketChanging(string value);
    partial void OnticketChanged();
    partial void OndateCreatedChanging(System.DateTime value);
    partial void OndateCreatedChanged();
    partial void OnlastAccessChanging(System.DateTime value);
    partial void OnlastAccessChanged();
    partial void OnpermissionChanging(int value);
    partial void OnpermissionChanged();
    #endregion
		
		public account()
		{
			this._alias = new EntitySet<alias>(new Action<alias>(this.attach_alias), new Action<alias>(this.detach_alias));
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_password", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[Column(Storage="_ticket", DbType="VarChar(128)")]
		public string ticket
		{
			get
			{
				return this._ticket;
			}
			set
			{
				if ((this._ticket != value))
				{
					this.OnticketChanging(value);
					this.SendPropertyChanging();
					this._ticket = value;
					this.SendPropertyChanged("ticket");
					this.OnticketChanged();
				}
			}
		}
		
		[Column(Storage="_dateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime dateCreated
		{
			get
			{
				return this._dateCreated;
			}
			set
			{
				if ((this._dateCreated != value))
				{
					this.OndateCreatedChanging(value);
					this.SendPropertyChanging();
					this._dateCreated = value;
					this.SendPropertyChanged("dateCreated");
					this.OndateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_lastAccess", DbType="DateTime NOT NULL")]
		public System.DateTime lastAccess
		{
			get
			{
				return this._lastAccess;
			}
			set
			{
				if ((this._lastAccess != value))
				{
					this.OnlastAccessChanging(value);
					this.SendPropertyChanging();
					this._lastAccess = value;
					this.SendPropertyChanged("lastAccess");
					this.OnlastAccessChanged();
				}
			}
		}
		
		[Column(Storage="_permission", DbType="Int NOT NULL")]
		public int permission
		{
			get
			{
				return this._permission;
			}
			set
			{
				if ((this._permission != value))
				{
					this.OnpermissionChanging(value);
					this.SendPropertyChanging();
					this._permission = value;
					this.SendPropertyChanged("permission");
					this.OnpermissionChanged();
				}
			}
		}
		
		[Association(Name="account_alia", Storage="_alias", OtherKey="account")]
		public EntitySet<alias> alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				this._alias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_alias(alias entity)
		{
			this.SendPropertyChanging();
			entity.account1 = this;
		}
		
		private void detach_alias(alias entity)
		{
			this.SendPropertyChanging();
			entity.account1 = null;
		}
	}
	
	[Table(Name="dbo.zone")]
	public partial class zone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _password;
		
		private string _name;
		
		private string _description;
		
		private string _notice;
		
		private short _active;
		
		private EntitySet<player> _players;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnnoticeChanging(string value);
    partial void OnnoticeChanged();
    partial void OnactiveChanging(short value);
    partial void OnactiveChanged();
    #endregion
		
		public zone()
		{
			this._players = new EntitySet<player>(new Action<player>(this.attach_players), new Action<player>(this.detach_players));
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_description", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_notice", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string notice
		{
			get
			{
				return this._notice;
			}
			set
			{
				if ((this._notice != value))
				{
					this.OnnoticeChanging(value);
					this.SendPropertyChanging();
					this._notice = value;
					this.SendPropertyChanged("notice");
					this.OnnoticeChanged();
				}
			}
		}
		
		[Column(Storage="_active", DbType="SmallInt NOT NULL")]
		public short active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[Association(Name="zone_player", Storage="_players", OtherKey="zone")]
		public EntitySet<player> players
		{
			get
			{
				return this._players;
			}
			set
			{
				this._players.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_players(player entity)
		{
			this.SendPropertyChanging();
			entity.zone1 = this;
		}
		
		private void detach_players(player entity)
		{
			this.SendPropertyChanging();
			entity.zone1 = null;
		}
	}
	
	[Table(Name="dbo.alias")]
	public partial class alias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _account;
		
		private string _name;
		
		private System.DateTime _creation;
		
		private EntitySet<player> _players;
		
		private EntityRef<account> _account1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnaccountChanging(long value);
    partial void OnaccountChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncreationChanging(System.DateTime value);
    partial void OncreationChanged();
    #endregion
		
		public alias()
		{
			this._players = new EntitySet<player>(new Action<player>(this.attach_players), new Action<player>(this.detach_players));
			this._account1 = default(EntityRef<account>);
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_account", DbType="BigInt NOT NULL")]
		public long account
		{
			get
			{
				return this._account;
			}
			set
			{
				if ((this._account != value))
				{
					if (this._account1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnaccountChanging(value);
					this.SendPropertyChanging();
					this._account = value;
					this.SendPropertyChanged("account");
					this.OnaccountChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_creation", DbType="DateTime NOT NULL")]
		public System.DateTime creation
		{
			get
			{
				return this._creation;
			}
			set
			{
				if ((this._creation != value))
				{
					this.OncreationChanging(value);
					this.SendPropertyChanging();
					this._creation = value;
					this.SendPropertyChanged("creation");
					this.OncreationChanged();
				}
			}
		}
		
		[Association(Name="alia_player", Storage="_players", OtherKey="alias")]
		public EntitySet<player> players
		{
			get
			{
				return this._players;
			}
			set
			{
				this._players.Assign(value);
			}
		}
		
		[Association(Name="account_alia", Storage="_account1", ThisKey="account", IsForeignKey=true)]
		public account account1
		{
			get
			{
				return this._account1.Entity;
			}
			set
			{
				account previousValue = this._account1.Entity;
				if (((previousValue != value) 
							|| (this._account1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._account1.Entity = null;
						previousValue.alias.Remove(this);
					}
					this._account1.Entity = value;
					if ((value != null))
					{
						value.alias.Add(this);
						this._account = value.id;
					}
					else
					{
						this._account = default(long);
					}
					this.SendPropertyChanged("account1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_players(player entity)
		{
			this.SendPropertyChanging();
			entity.alias1 = this;
		}
		
		private void detach_players(player entity)
		{
			this.SendPropertyChanging();
			entity.alias1 = null;
		}
	}
	
	[Table(Name="dbo.squad")]
	public partial class squad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
		private string _password;
		
		private System.DateTime _dateCreated;
		
		private EntitySet<player> _players;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OndateCreatedChanging(System.DateTime value);
    partial void OndateCreatedChanged();
    #endregion
		
		public squad()
		{
			this._players = new EntitySet<player>(new Action<player>(this.attach_players), new Action<player>(this.detach_players));
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_password", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[Column(Storage="_dateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime dateCreated
		{
			get
			{
				return this._dateCreated;
			}
			set
			{
				if ((this._dateCreated != value))
				{
					this.OndateCreatedChanging(value);
					this.SendPropertyChanging();
					this._dateCreated = value;
					this.SendPropertyChanged("dateCreated");
					this.OndateCreatedChanged();
				}
			}
		}
		
		[Association(Name="squad_player", Storage="_players", OtherKey="squad")]
		public EntitySet<player> players
		{
			get
			{
				return this._players;
			}
			set
			{
				this._players.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_players(player entity)
		{
			this.SendPropertyChanging();
			entity.squad1 = this;
		}
		
		private void detach_players(player entity)
		{
			this.SendPropertyChanging();
			entity.squad1 = null;
		}
	}
}
#pragma warning restore 1591
