// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace db.packets
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Acknowledge : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Acknowledge GetRootAsAcknowledge(ByteBuffer _bb) { return GetRootAsAcknowledge(_bb, new Acknowledge()); }
  public static Acknowledge GetRootAsAcknowledge(ByteBuffer _bb, Acknowledge obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyAcknowledge(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, AcknowledgeVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Acknowledge __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int MsgId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Message { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<db.packets.Acknowledge> CreateAcknowledge(FlatBufferBuilder builder,
      int msg_id = 0,
      StringOffset messageOffset = default(StringOffset)) {
    builder.StartTable(2);
    Acknowledge.AddMessage(builder, messageOffset);
    Acknowledge.AddMsgId(builder, msg_id);
    return Acknowledge.EndAcknowledge(builder);
  }

  public static void StartAcknowledge(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMsgId(FlatBufferBuilder builder, int msgId) { builder.AddInt(0, msgId, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(1, messageOffset.Value, 0); }
  public static Offset<db.packets.Acknowledge> EndAcknowledge(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<db.packets.Acknowledge>(o);
  }
  public static void FinishAcknowledgeBuffer(FlatBufferBuilder builder, Offset<db.packets.Acknowledge> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedAcknowledgeBuffer(FlatBufferBuilder builder, Offset<db.packets.Acknowledge> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class AcknowledgeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MsgId*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Message*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
