// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace db.packets
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Error : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Error GetRootAsError(ByteBuffer _bb) { return GetRootAsError(_bb, new Error()); }
  public static Error GetRootAsError(ByteBuffer _bb, Error obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyError(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ErrorVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Error __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int MsgId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Reason { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetReasonBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetReasonBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetReasonArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<db.packets.Error> CreateError(FlatBufferBuilder builder,
      int msg_id = 0,
      StringOffset reasonOffset = default(StringOffset)) {
    builder.StartTable(2);
    Error.AddReason(builder, reasonOffset);
    Error.AddMsgId(builder, msg_id);
    return Error.EndError(builder);
  }

  public static void StartError(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMsgId(FlatBufferBuilder builder, int msgId) { builder.AddInt(0, msgId, 0); }
  public static void AddReason(FlatBufferBuilder builder, StringOffset reasonOffset) { builder.AddOffset(1, reasonOffset.Value, 0); }
  public static Offset<db.packets.Error> EndError(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<db.packets.Error>(o);
  }
  public static void FinishErrorBuffer(FlatBufferBuilder builder, Offset<db.packets.Error> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedErrorBuffer(FlatBufferBuilder builder, Offset<db.packets.Error> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ErrorVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MsgId*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Reason*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
