# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Windows
      run: dotnet publish ./dotnetcore/InfServerNetCore.sln --output ./releases/windows -c Release -r win-x64

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-windows
        path: ./releases/windows/*  
    
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build Linux
      run: dotnet publish ./dotnetcore/InfServerNetCore.sln --output ./releases/linux -c Release -r linux-x64

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-linux
        path: ./releases/linux/*  

  build-publish:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]

    steps:
    - name: Get Date Format
      uses: kaven-universe/github-action-current-date-time@v1.4.0
      id: timestep
      with:
        format: "YYYY_MM_DD_HH_mm_ss_SSS"

    - name: Download windows artifact
      uses: actions/download-artifact@v4
      with:
        name: release-windows
        path: ./releases-windows
        
    - name: Download linux artifact
      uses: actions/download-artifact@v4
      with:
        name: release-linux
        path: ./releases-linux

    - name: Zip Windows Artifact
      run: zip release-windows.zip ./releases-windows/*

    - name: Zip Linux Artifact
      run: zip release-linux.zip ./releases-linux/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Release-${{ steps.timestep.outputs.time }}
        release_name: Release ${{ steps.timestep.outputs.time }}
        draft: false
        prerelease: false

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-windows.zip
        asset_name: release-windows.zip
        asset_content_type: application/zip

    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-linux.zip
        asset_name: release-linux.zip
        asset_content_type: application/zip
      
