# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows-infrastructure:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Windows Infra DirServ
      run: dotnet publish ./dotnetcore/DirectoryServer/DirectoryServer.csproj --output ./releases/windows-infrastructure/directory-server -c Release -r win-x64

    - name: Build Windows Infra DbServ
      run: dotnet publish ./dotnetcore/DatabaseServer/DatabaseServer.csproj --output ./releases/windows-infrastructure/database-server -c Release -r win-x64

    - name: Build Windows Infra AcctServer
      run: dotnet publish ./dotnetcore/AccountServer/AccountServer.csproj --output ./releases/windows-infrastructure/account-server -c Release -r win-x64

    - name: Build Windows Infra Daemon
      run: dotnet publish ./dotnetcore/Daemon/Daemon.csproj --output ./releases/windows-infrastructure/daemon -c Release -r win-x64

    - name: Upload Windows Infra Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-windows-infrastructure
        path: ./releases/windows-infrastructure/

  build-linux-infrastructure:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Linux Infra DirServ
      run: dotnet publish ./dotnetcore/DirectoryServer/DirectoryServer.csproj --output ./releases/linux-infrastructure/directory-server -c Release -r linux-x64

    - name: Build Linux Infra DbServ
      run: dotnet publish ./dotnetcore/DatabaseServer/DatabaseServer.csproj --output ./releases/linux-infrastructure/database-server -c Release -r linux-x64

    - name: Build Linux Infra AcctServer
      run: dotnet publish ./dotnetcore/AccountServer/AccountServer.csproj --output ./releases/linux-infrastructure/account-server -c Release -r linux-x64

    - name: Build Linux Infra Daemon
      run: dotnet publish ./dotnetcore/Daemon/Daemon.csproj --output ./releases/linux-infrastructure/daemon -c Release -r linux-x64

    - name: Upload Linux Infra Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-linux-infrastructure
        path: ./releases/linux-infrastructure/
  
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Windows
      run: dotnet publish ./dotnetcore/Server/ZoneServer.csproj --output ./releases/windows -c Release -r win-x64

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-windows
        path: ./releases/windows/*  
    
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build Linux
      run: dotnet publish ./dotnetcore/Server/ZoneServer.csproj --output ./releases/linux -c Release -r linux-x64

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-linux
        path: ./releases/linux/*  

  build-publish:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-windows-infrastructure, build-linux-infrastructure]

    steps:
    - name: Get Date Format
      uses: kaven-universe/github-action-current-date-time@v1.4.0
      id: timestep
      with:
        format: "DD-MM-YYYY-HH.mm"

    - name: Download windows infrastructure artifact
      uses: actions/download-artifact@v4
      with:
        name: release-windows-infrastructure
        path: ./releases-windows-infrastructure

    - name: Download linux infrastructure artifact
      uses: actions/download-artifact@v4
      with:
        name: release-linux-infrastructure
        path: ./releases-linux-infrastructure

    - name: Download windows artifact
      uses: actions/download-artifact@v4
      with:
        name: release-windows
        path: ./releases-windows
        
    - name: Download linux artifact
      uses: actions/download-artifact@v4
      with:
        name: release-linux
        path: ./releases-linux

    - name: Zip Windows Infrastructure Artifact
      run: zip -r release-windows-infrastructure.zip ./releases-windows-infrastructure/*

    - name: Zip Linux Infrastructure Artifact
      run: zip -r release-linux-infrastructure.zip ./releases-linux-infrastructure/*

    - name: Zip Windows Artifact
      run: zip -r release-windows.zip ./releases-windows/*

    - name: Zip Linux Artifact
      run: zip -r release-linux.zip ./releases-linux/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Release-${{ steps.timestep.outputs.time }}
        release_name: Release ${{ steps.timestep.outputs.time }}
        draft: false
        prerelease: false

    - name: upload windows infrastructure artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-windows-infrastructure.zip
        asset_name: release-windows-infrastructure.zip
        asset_content_type: application/zip

    - name: upload linux infrastructure artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-linux-infrastructure.zip
        asset_name: release-linux-infrastructure.zip
        asset_content_type: application/zip

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-windows.zip
        asset_name: release-windows.zip
        asset_content_type: application/zip

    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-linux.zip
        asset_name: release-linux.zip
        asset_content_type: application/zip
      
